# Generated by Django 6.0.1 on 2026-02-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Gender', models.CharField(max_length=20)),
                ('Qualification', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
                ('Password', models.CharField(max_length=30)),
                ('Profile_picture', models.ImageField(upload_to='image')),
                ('Music', models.FileField(upload_to='audio')),
                ('Video', models.FileField(upload_to='video')),
                ('Resume', models.FileField(upload_to='doc')),
            ],
        ),
    ]
