# Generated by Django 6.0.1 on 2026-02-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Contact',
            field=models.BigIntegerField(),
        ),
    ]
